services:
  backend:
    build:
      context: ../preparcial_web # Así se llamaba el back en mi computador. Por favor cambiar a bookstore_back o el nombre necesario.
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"  
    environment:
      - SERVER_PORT=8080
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/api/books"]
      interval: 10s
      timeout: 3s
      retries: 5

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE=http://backend:8080/api
      - BACKEND_URL=http://backend:8080/api/books
    ports:
      - "3000:3000"

networks:
  default:
    name: preparcial-web-final
